# Generated by Django 2.0.6 on 2018-06-07 18:21

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('comisaria', models.CharField(blank=True, default='Comisaria 1', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Denunciante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nro_documento', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sexo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=100, null=True)),
                ('precio_por_persona', models.FloatField(blank=True, null=True)),
                ('cantidad_minima_personas', models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_maxima_personas', models.PositiveIntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, default=datetime.time(15, 21, 17, 315741), null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDenuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExcursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nro_documento', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Nacionalidad')),
            ],
        ),
        migrations.AddField(
            model_name='excursion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.TipoExcursion'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='turistas',
            field=models.ManyToManyField(to='restapp.Turista'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='denunciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Denunciante'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='tipo_denuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.TipoDenuncia'),
        ),
    ]
